### ISSUE TITLE
WebcamInput > ProcessFrame, what if a computer does not have a camera.

### ISSUE THREAD

**Issue by dogecade** [dogecade/ProtingaVizija#8]
My desktop does not have a camera, so as I understand it returns a nullpointerexception and that is not thought through.

**Comment by DeividasBrazenas** [comment]
Closing this issue. Fixed in this commit: https://github.com/dogecade/ProtingaVizija/commit/b66d3b68a5190b14ba0adb85057a3a18a299a5c7
